repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--ignore, "D100,D104,D107,D102,D202,D203,D213,D413,D416"]
        exclude: tests
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-yaml
        exclude: ^tests/|^conda\.recipe/
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: pretty-format-json
        exclude: ipynb
        args: [--autofix]
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: tests/data
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-typing-imports==1.12.0
          - flake8-builtins==1.5.3
          - flake8-bugbear==22.1.11
          - flake8-isort==4.1.1
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --clear-output --inplace
