name: cpu-demos
channels:
  - conda-forge
dependencies:
  - cosapp
  - numpy
  - plotly<6.0.0
  - cosapp_lab
  - pytest
  - pyoccad
  - pythreejs
  - joblib
  - scikit-learn
  - pre-commit
  - ipywidgets
